project:
  type: website
  output-dir: docs
website:
  title: "Waquas Mohammad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: black
    css: styles.css
    toc: true



